### ISSUE TITLE
请问这是什么原因

### ISSUE THREAD

**Issue by ParamXw** [hh22814/SVDF#2]
![image](https://github.com/user-attachments/assets/7c112d28-a6da-40b7-9e68-ed5bfcd61daa)

**Comment by ParamXw** [comment]
请问您用的是哪个版本的tf

**Comment by coopsor** [comment]
> ![image](https://private-user-images.githubusercontent.com/145409352/389526496-7c112d28-a6da-40b7-9e68-ed5bfcd61daa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NTg3MjgsIm5iZiI6MTczMzc1ODQyOCwicGF0aCI6Ii8xNDU0MDkzNTIvMzg5NTI2NDk2LTdjMTEyZDI4LWE2ZGEtNDBiNy05ZTY4LWVkNWJmY2Q2MWRhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQxNTMzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDY5OTAwNTk0ZmJkNmQzNWRjOTBkOWM0MWY2NDk4ZjA4NGY0YzNiM2Q3NGJmMWM0ZjZiYzIzOWMyNzM2M2RkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.diPsC34K56LkReNuadfxBSobB-qRqF4txJC3MRyM1Xw)
这里ref参数是指定染色体，而不是fa文件，这个参数你可以去掉，SVDF会默认运行全部染色体。我认为这个是输出SV个数为0的原因，并导致后续了报错。

**Comment by coopsor** [comment]
> 请问您用的是哪个版本的tf

实验测试是在2.6.0版本下运行的

**Comment by ParamXw** [comment]
> > 请问您用的是哪个版本的tf
> 
> 实验测试是在2.6.0版本下运行的

谢谢您的解答！给您一个建议，因为tensorflow高版本并不兼容低版本，可以把版本那里的大于号去掉

**Comment by coopsor** [comment]
> > > 请问您用的是哪个版本的tf
> > 
> > 
> > 实验测试是在2.6.0版本下运行的
> 
> 谢谢您的解答！给您一个建议，因为tensorflow高版本并不兼容低版本，可以把版本那里的大于号去掉

好的！十分感谢你的建议
